info:
  name: RD - Dispositivo di Distribuzione - Molecola (Development)
  artifact: '@project.artifactId@'
  version: '@project.version@'

server:
  port: 8882
  servlet:
    context-path: /spike

spring:
  application:
    name: rd-distribution
  rabbitmq:
    addresses: amqps://server
  cloud:
    stream:
      rabbit:
        bindings:
          requestChannel:
            producer:
              routingKeyExpression: "'rdRequestChannel'"

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka

rd:
  username: rd
  password: rd
