server:
  port: 8881
  servlet:
    context-path: /rdd

spring:
  application:
    name: rdd-spike
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka
zuul:
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 15000
  ignored-services: '*'
  routes:
    rdd-distribution:
      path: /distribution/**
      serviceId: rdd-distribution
      stripPrefix: true
      sensitiveHeaders:

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 32000


ribbon:
  ReadTimeout: 15000
  connection-timeout: 15000
  eureka:
    enabled: true
