info:
  name: RDD - Registro Digitale Ditribuito - Dispositivo di Distribuzione - Molecola (Development)
  artifact: '@project.artifactId@'
  version: '@project.version@'

server:
  port: 8882
  servlet:
    context-path: /spike

spring:
  application:
    name: rdd-distribution

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka
