info:
  name: RDD - Dispositivo di Distribuzione - Molecola (Development)
  artifact: '@project.artifactId@'
  version: '@project.version@'

server:
  port: 8882
  servlet:
    context-path: /spike

spring:
  application:
    name: rdd-distribution
  rabbitmq:
    addresses: amqps://server
  cloud:
    stream:
      bindings:
        entryPropositionChannel:
          destination: rdd.topic
      rabbit:
        bindings:
          entryPropositionChannel:
            producer:
              routingKeyExpression: "'rddEntryPropositionChannel'"

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka

rdd:
  username: rdd
  password: rdd
