spring:
  application:
    name: rd-node-A
  rabbitmq:
    addresses: amqp://test
  cloud:
    stream:
      bindings:
        requestChannel:
          destination: requestChannel
          group: nodeGroup
        requestIntegrityChannel:
          destination: requestIntegrityChannel
          group: nodeGroup
        responseChannel:
          producer:
            routingKeyExpression: "'rdResponseChannel'"
        distributionChannel:
          destination: distributionChannel
  data:
    mongodb:
      uri: mongodb+srv://rd_node
      database: rd-A

server:
  port: 8884

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka

rd:
  startup: false
  difficult:
    level: 1
  spike:
    url: http://localhost:8881/rd/distribution/spike
