spring:
  application:
    name: rdc-node-A
  rabbitmq:
    addresses: amqp://test
  cloud:
    stream:
      bindings:
        requestChannel:
          destination: requestChannel
          group: nodeGroup
        responseChannel:
          producer:
            routingKeyExpression: "'rdcResponseChannel'"
        distributionChannel:
          destination: distributionChannel
  data:
    mongodb:
      uri: mongodb+srv://rdc_node
      database: rdc-A

server:
  port: 8884

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka

difficult:
  level: 1

required:
  validation:
    number: 0

spike:
  url: http://localhost:8881/rdc/distribution/spike
